Fixed minor Login errors
KinveyApps/sample-Groceries pull request #2
Opened 2018-02-04 16:53 UTC by bnowak008

1. ngmodel in login.component.html configured to username instead of email
2. login.service.ts login function is being passed user.username instead of user.email. (user.username is never assigned).
3. Changed import of the email validator to the typescript import.

2018-02-08 13:54 UTC, thomasconner requested changes

2018-02-08 13:54 UTC, thomasconner commented on app/shared/user.model.ts
>    username?: string;
Lets remove the `username` property of `User` since it is not being used anymore.

2018-02-08 13:54 UTC, thomasconner commented on app/shared/user.model.ts
>    username?: string;
Should the `email` property not be optional anymore either? It seems like it shouldn't to me.

2018-02-25 20:00 UTC, bnowak008 reviewed
Agreed username can be completely removed.

2018-02-26 02:15 UTC, thomasconner approved these changes

2018-02-26 02:16 UTC, merged